filter:
    excluded_paths:
        - languages/*

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_mess_detector: true
    php_analyzer: true
    php_cpd: true
    php_pdepend: true
    php_code_sniffer:
        config:
            standard: "WordPress"